Repository vaadin/vaadin-text-field, pull requests merged in 2019-01, with the labels that each got.

#294 Add autoselect
  src/vaadin-text-field-mixin.html
  test/text-field.html
Labels: in review

#291 Add visualisation when invalid input is prevented
  src/vaadin-text-field-mixin.html
  src/vaadin-text-field.html
  test/validation.html
  test/visual/screens/vaadin-text-field/text-field-1-lumo/text-field-1/chrome.png
  test/visual/screens/vaadin-text-field/text-field-1-lumo/text-field-1/firefox.png
  test/visual/screens/vaadin-text-field/text-field-1-material/text-field-1/chrome.png
  test/visual/screens/vaadin-text-field/text-field-1-material/text-field-1/firefox.png
  test/visual/vaadin-text-field/text-field-1.html
  theme/lumo/vaadin-text-field-styles.html
  theme/material/vaadin-text-field-styles.html
Labels: in review

#299 Don't flex-grow the input-field part of a text-field
  src/vaadin-text-field-mixin.html
  test/text-field.html
Labels: in progress

#290 Add <vaadin-email-field> component
  README.md
  bower.json
  demo/demos.json
  demo/email-field-demos.html
  demo/index.html
  src/vaadin-email-field.html
  test/email-field.html
  test/test-suites.js
  theme/lumo/vaadin-email-field.html
  theme/material/vaadin-email-field.html
  vaadin-directory-description.md
  vaadin-email-field.html
Labels: design

#110 vaadin-number-field element
  bower.json
  demo/demos.json
  demo/index.html
  demo/number-field-demos.html
  src/vaadin-number-field.html
  test/number-field.html
  test/test-suites.js
  test/visual/screens/vaadin-text-field/number-field-lumo/number-field/chrome.png
  test/visual/screens/vaadin-text-field/number-field-lumo/number-field/firefox.png
  test/visual/screens/vaadin-text-field/number-field-material/number-field/chrome.png
  test/visual/screens/vaadin-text-field/number-field-material/number-field/firefox.png
  test/visual/screens/vaadin-text-field/number-field/number-field/chrome.png
  test/visual/screens/vaadin-text-field/number-field/number-field/edge.png
  test/visual/screens/vaadin-text-field/number-field/number-field/firefox.png
  test/visual/screens/vaadin-text-field/number-field/number-field/ie.png
  test/visual/test.js
  test/visual/vaadin-number-field/number-field.html
  theme/lumo/vaadin-number-field-styles.html
  theme/lumo/vaadin-number-field.html
  theme/material/vaadin-number-field-styles.html
  theme/material/vaadin-number-field.html
  vaadin-number-field.html
Labels: design, enhancement, requires user testing

#300 fix: ensure slotchange input listeners removal does not throw
  src/vaadin-text-field-mixin.html
  test/text-field.html
Labels: in review

#302 Copy textarea style overrides from Lumo to Material
  test/visual/screens/vaadin-text-field/text-area-1-lumo/text-area-1/chrome.png
  test/visual/screens/vaadin-text-field/text-area-1-lumo/text-area-1/firefox.png
  test/visual/screens/vaadin-text-field/text-area-1-material/text-area-1/chrome.png
  test/visual/screens/vaadin-text-field/text-area-1-material/text-area-1/firefox.png
  test/visual/vaadin-text-area/text-area-1.html
  theme/material/vaadin-text-area-styles.html
Labels: in progress

#305 Align stepper buttons to middle
  test/visual/screens/vaadin-text-field/number-field-lumo/number-field/chrome.png
  test/visual/screens/vaadin-text-field/number-field-lumo/number-field/firefox.png
  test/visual/screens/vaadin-text-field/number-field-material/number-field/chrome.png
  theme/lumo/vaadin-number-field-styles.html
  theme/material/vaadin-number-field-styles.html
Labels: in review

#303 Fix setting min/max value with controls
  src/vaadin-number-field.html
  test/number-field.html
Labels: in review

#307 Fix value control behaviour when value is out of range
  src/vaadin-number-field.html
  test/number-field.html
Labels: in progress
